#include "renderer/Drivers/OpenGL_GLSL/OpenGL15Driver/OpenGL_15_ConstantsTables.h"
#include "renderer/Drivers/OpenGL_GLSL/GLEW/glew.h"

namespace renderer
{
namespace drivers
{
namespace opengl_glsl_15
{
namespace OpenGL_GLSL_Tables
{


unsigned	MatrixMode[] = {
		GL_MODELVIEW,	/*VIEW*/
		GL_PROJECTION,
		GL_PROJECTION,	/*PROJECTION*/
		GL_TEXTURE0_ARB,	/*TEXTURE0*/
		GL_TEXTURE1_ARB,	/*TEXTURE1*/
		GL_TEXTURE2_ARB,	/*TEXTURE2*/
		GL_TEXTURE3_ARB,	/*TEXTURE3*/
		GL_TEXTURE4_ARB,	/*TEXTURE4*/
		GL_TEXTURE5_ARB,	/*TEXTURE5*/
		GL_TEXTURE6_ARB,	/*TEXTURE6*/
		GL_TEXTURE7_ARB,	/*TEXTURE7*/
		GL_TEXTURE8_ARB,	/*TEXTURE8*/
		GL_TEXTURE9_ARB,	/*TEXTURE9*/
		GL_TEXTURE10_ARB,	/*TEXTURE10*/
		GL_TEXTURE11_ARB,	/*TEXTURE11*/
		GL_TEXTURE12_ARB,	/*TEXTURE12*/
		GL_TEXTURE13_ARB,	/*TEXTURE13*/
		GL_TEXTURE14_ARB,	/*TEXTURE14*/
		GL_TEXTURE15_ARB,	/*TEXTURE15*/
		GL_TEXTURE16_ARB,	/*TEXTURE16*/
		GL_TEXTURE17_ARB,	/*TEXTURE17*/
		GL_TEXTURE18_ARB,	/*TEXTURE18*/
		GL_TEXTURE19_ARB,	/*TEXTURE19*/
		GL_TEXTURE20_ARB,	/*TEXTURE20*/
		GL_TEXTURE21_ARB,	/*TEXTURE21*/
		GL_TEXTURE22_ARB,	/*TEXTURE22*/
		GL_TEXTURE23_ARB,	/*TEXTURE23*/
		GL_TEXTURE24_ARB,	/*TEXTURE24*/
		GL_TEXTURE25_ARB,	/*TEXTURE25*/
		GL_TEXTURE26_ARB,	/*TEXTURE26*/
		GL_TEXTURE27_ARB,	/*TEXTURE27*/
		GL_TEXTURE28_ARB,	/*TEXTURE28*/
		GL_TEXTURE29_ARB,	/*TEXTURE29*/
		GL_TEXTURE30_ARB,	/*TEXTURE30*/
		GL_TEXTURE31_ARB 	/*TEXTURE31*/
};


unsigned	TextureUnit[] = {
		GL_TEXTURE0_ARB,	/*TEXTURE0*/
		GL_TEXTURE1_ARB,	/*TEXTURE1*/
		GL_TEXTURE2_ARB,	/*TEXTURE2*/
		GL_TEXTURE3_ARB,	/*TEXTURE3*/
		GL_TEXTURE4_ARB,	/*TEXTURE4*/
		GL_TEXTURE5_ARB,	/*TEXTURE5*/
		GL_TEXTURE6_ARB,	/*TEXTURE6*/
		GL_TEXTURE7_ARB,	/*TEXTURE7*/
		GL_TEXTURE8_ARB,	/*TEXTURE8*/
		GL_TEXTURE9_ARB,	/*TEXTURE9*/
		GL_TEXTURE10_ARB,	/*TEXTURE10*/
		GL_TEXTURE11_ARB,	/*TEXTURE11*/
		GL_TEXTURE12_ARB,	/*TEXTURE12*/
		GL_TEXTURE13_ARB,	/*TEXTURE13*/
		GL_TEXTURE14_ARB,	/*TEXTURE14*/
		GL_TEXTURE15_ARB,	/*TEXTURE15*/
		GL_TEXTURE16_ARB,	/*TEXTURE16*/
		GL_TEXTURE17_ARB,	/*TEXTURE17*/
		GL_TEXTURE18_ARB,	/*TEXTURE18*/
		GL_TEXTURE19_ARB,	/*TEXTURE19*/
		GL_TEXTURE20_ARB,	/*TEXTURE20*/
		GL_TEXTURE21_ARB,	/*TEXTURE21*/
		GL_TEXTURE22_ARB,	/*TEXTURE22*/
		GL_TEXTURE23_ARB,	/*TEXTURE23*/
		GL_TEXTURE24_ARB,	/*TEXTURE24*/
		GL_TEXTURE25_ARB,	/*TEXTURE25*/
		GL_TEXTURE26_ARB,	/*TEXTURE26*/
		GL_TEXTURE27_ARB,	/*TEXTURE27*/
		GL_TEXTURE28_ARB,	/*TEXTURE28*/
		GL_TEXTURE29_ARB,	/*TEXTURE29*/
		GL_TEXTURE30_ARB,	/*TEXTURE30*/
		GL_TEXTURE31_ARB 	/*TEXTURE31*/
};


unsigned	TextureType[] = {
		GL_TEXTURE_1D,	/*TEXTURE_1D*/
		GL_TEXTURE_2D,	/*TEXTURE_2D*/
		GL_TEXTURE_3D,	/*TEXTURE_3D*/
		GL_TEXTURE_CUBE_MAP_ARB,	/*TEXTURE_CUBE*/
		GL_TEXTURE_RECTANGLE_ARB 	/*TEXTURE_RECTANGLE*/
};


unsigned	TextureInternalFormat[] = {
		GL_ALPHA4,	/*ALPHA4*/
		GL_ALPHA8,	/*ALPHA8*/
		GL_ALPHA12,	/*ALPHA12*/
		GL_ALPHA16,	/*ALPHA16*/
		GL_LUMINANCE4,	/*LUMINANCE4*/
		GL_LUMINANCE8,	/*LUMINANCE8*/
		GL_LUMINANCE12,	/*LUMINANCE12*/
		GL_LUMINANCE16,	/*LUMINANCE16*/
		GL_LUMINANCE4_ALPHA4,	/*LUMINANCE4_ALPHA4*/
		GL_LUMINANCE6_ALPHA2,	/*LUMINANCE6_ALPHA2*/
		GL_LUMINANCE8_ALPHA8,	/*LUMINANCE8_ALPHA8*/
		GL_LUMINANCE12_ALPHA4,	/*LUMINANCE12_ALPHA4*/
		GL_LUMINANCE12_ALPHA12,	/*LUMINANCE12_ALPHA12*/
		GL_LUMINANCE16_ALPHA16,	/*LUMINANCE16_ALPHA16*/
		GL_INTENSITY4,	/*INTENSITY4*/
		GL_INTENSITY8,	/*INTENSITY8*/
		GL_INTENSITY12,	/*INTENSITY12*/
		GL_INTENSITY16,	/*INTENSITY16*/
		GL_R3_G3_B2,	/*R3_G3_B2*/
		GL_RGB4,	/*RGB4*/
		GL_RGB5,	/*RGB5*/
		GL_RGB8,	/*RGB8*/
		GL_RGB10,	/*RGB10*/
		GL_RGB12,	/*RGB12*/
		GL_RGB16,	/*RGB16*/
		GL_RGBA2,	/*RGBA2*/
		GL_RGBA4,	/*RGBA4*/
		GL_RGB5_A1,	/*RGB5_A1*/
		GL_RGB8,	/*RGBA8*/
		GL_RGB10_A2,	/*RGB10_A2*/
		GL_RGBA12,	/*RGBA12*/
		GL_RGBA16,	/*RGBA16*/
		GL_RGBA32F_ARB,	/*RGBA32F*/
		GL_RGBA16F_ARB,	/*RGBA16F*/
		GL_RGB32F_ARB,	/*RGB32F*/
		GL_RGB16F_ARB,	/*RGB16F*/
		GL_INTENSITY32F_ARB,	/*INTENSITY32F*/
		GL_INTENSITY16F_ARB,	/*INTENSITY16F*/
		GL_ALPHA32F_ARB,	/*ALPHA32F*/
		GL_ALPHA16F_ARB,	/*ALPHA16F*/
		GL_LUMINANCE32F_ARB,	/*LUMIANCE32F*/
		GL_LUMINANCE16F_ARB,	/*LUMIANCE16F*/
		GL_LUMINANCE_ALPHA32F_ARB,	/*LUMIANCE_ALPHA32F*/
		GL_LUMINANCE_ALPHA16F_ARB,	/*LUMIANCE_ALPHA16F*/
		GL_DEPTH_COMPONENT16,	/*DEPTH16*/
		GL_DEPTH_COMPONENT24,	/*DEPTH24*/
		GL_DEPTH_COMPONENT32,	/*DEPTH32*/
		GL_STENCIL_INDEX1_EXT,	/*STENCIL1*/
		GL_STENCIL_INDEX4_EXT,	/*STENCIL4*/
		GL_STENCIL_INDEX8_EXT,	/*STENCIL8*/
		GL_STENCIL_INDEX16_EXT,	/*STENCIL16*/
		GL_DEPTH24_STENCIL8_EXT,	/*DEPTH24_STENCIL8*/
		GL_COMPRESSED_RGB_S3TC_DXT1_EXT,	/*RGB_DXT1*/
		GL_COMPRESSED_RGBA_S3TC_DXT1_EXT,	/*RGBA_DXT1*/
		GL_COMPRESSED_RGBA_S3TC_DXT3_EXT,	/*RGBA_DXT3*/
		GL_COMPRESSED_RGBA_S3TC_DXT5_EXT    	/*RGBA_DXT5*/
};


unsigned	TextureStorage[] = {
		GL_UNSIGNED_BYTE,	/*UNSIGNED_BYTE*/
		GL_BYTE,	/*BYTE*/
		GL_UNSIGNED_SHORT,	/*UNSIGNED_SHORT*/
		GL_SHORT,	/*SHORT*/
		GL_UNSIGNED_INT,	/*UNSIGNED_INT*/
		GL_INT,	/*INT*/
		GL_FLOAT 	/*FLOAT*/
};


unsigned	TextureFormat[] = {
		GL_COLOR_INDEX,	/*COLOR_INDEX*/
		GL_RED,	/*RED*/
		GL_GREEN,	/*GREEN*/
		GL_BLUE,	/*BLUE*/
		GL_ALPHA,	/*ALPHA*/
		GL_RGB,	/*RGB*/
		GL_RGBA,	/*RGBA*/
		GL_LUMINANCE,	/*LUMINANCE*/
		GL_LUMINANCE_ALPHA,	/*LUMINANCE_ALPHA*/
		GL_DEPTH_COMPONENT,	/*DEPTH*/
		GL_DEPTH_STENCIL_EXT   /*DEPTH_STENCIL*/
};

unsigned    TextureComponentsNumber[] = {
		1,//CI
		1,//R
		1,//G
		1,//B
		1,//A
		3,//RGB
		4,//RGBA
		1,//L
		2,//LA
		1,//D
		1,//DS

};

unsigned	TextureFiltering[] = {
		GL_NEAREST,	/*NEAREST*/
		GL_LINEAR,	/*LINEAR*/
		GL_NEAREST_MIPMAP_NEAREST,	/*NEAREST_MIPMAP_NEAREST*/
		GL_NEAREST_MIPMAP_LINEAR,	/*NEAREST_MIPMAP_LINEAR*/
		GL_LINEAR_MIPMAP_NEAREST,	/*LINEAR_MIPMAP_NEAREST*/
		GL_LINEAR_MIPMAP_LINEAR 	/*LINEAR_MIPMAP_LINEAR*/
};


unsigned	TextureClamping[] = {
		GL_CLAMP,	/*CLAMP*/
		GL_CLAMP_TO_EDGE,	/*CLAMP_TO_EDGE*/
		GL_CLAMP_TO_BORDER,	/*CLAMP_TO_BORDER*/
		GL_REPEAT 	/*REPEAT*/
};


unsigned	CubeTextureSide[] = {
		GL_TEXTURE_CUBE_MAP_POSITIVE_X_ARB,	/*X_POSITIVE*/
		GL_TEXTURE_CUBE_MAP_NEGATIVE_X_ARB,	/*X_NEGATIVE*/
		GL_TEXTURE_CUBE_MAP_POSITIVE_Y_ARB,	/*Y_POSITIVE*/
		GL_TEXTURE_CUBE_MAP_NEGATIVE_Y_ARB,	/*Y_NEGATIVE*/
		GL_TEXTURE_CUBE_MAP_POSITIVE_Z_ARB,	/*Z_POSITIVE*/
		GL_TEXTURE_CUBE_MAP_NEGATIVE_Z_ARB 	/*Z_NEGATIVE*/
};


unsigned	TextureCoord[] = {
		GL_S,	/*S*/
		GL_T,	/*T*/
		GL_R,	/*R*/
		GL_Q 	/*Q*/
};


unsigned	TextureGenMode[] = {
		GL_OBJECT_LINEAR,	/*OBJECT_LINEAR*/
		GL_EYE_LINEAR,	/*EYE_LINEAR*/
		GL_SPHERE_MAP,	/*SPHERE*/
		GL_REFLECTION_MAP_ARB, 	/*REFLECTION*/
		GL_NORMAL_MAP_ARB
};


unsigned	VBOType [] = {
		GL_ARRAY_BUFFER_ARB,	/*VERTEX*/
		GL_ELEMENT_ARRAY_BUFFER_ARB,	/*INDEX*/
		GL_PIXEL_PACK_BUFFER_ARB,	/*R2VB*/
		GL_PIXEL_UNPACK_BUFFER_ARB 	/*TEXTURE*/
};


unsigned	VBOUsage	[] = {
		GL_STREAM_DRAW,	/*STREAM_DRAW*/
		GL_STREAM_COPY,	/*STREAM_COPY*/
		GL_STREAM_READ,	/*STREAM_READ*/
		GL_DYNAMIC_DRAW,	/*DYNAMIC_DRAW*/
		GL_DYNAMIC_COPY,	/*DYNAMIC_COPY*/
		GL_DYNAMIC_READ,	/*DYNAMIC_READ*/
		GL_STATIC_DRAW,	/*STATIC_DRAW*/
		GL_STATIC_READ,	/*STATIC_READ*/
		GL_STATIC_COPY	/*STATIC_COPY*/
};


unsigned	VBOAccess [] = {
		GL_READ_ONLY_ARB,	/*READ_ONLY*/
		GL_WRITE_ONLY_ARB,	/*WRITE_ONLY*/
		GL_READ_WRITE_ARB 	/*READ_WRITE*/
};


unsigned	Primitive[] = {
		GL_POINTS,	/*POINTS*/
		GL_LINES,	/*LINES*/
		GL_LINES_ADJACENCY_EXT,	/*LINES_ADJACENCY*/
		GL_LINE_STRIP,	/*LINES_STRIP*/
		GL_LINE_STRIP_ADJACENCY_EXT,	/*LINES_STRIP_ADJACENCY*/
		GL_LINE_LOOP,	/*LINES_LOOP*/
		GL_TRIANGLES,	/*TRIANGLES*/
		GL_TRIANGLES_ADJACENCY_EXT,	/*TRIANGLES_ADJACENCY*/
		GL_TRIANGLE_STRIP,	/*TRIANGLES_STRIP*/
		GL_TRIANGLE_STRIP_ADJACENCY_EXT,	/*TRIANGLES_STRIP_ADJACENCY*/
		GL_TRIANGLE_FAN,	/*TRIANGLES_FAN*/
};


unsigned	RenderSide[] = {
		GL_FRONT,	/*FRONT*/
		GL_BACK,	/*BACK*/
		GL_FRONT_AND_BACK 	/*FRONT_AND_BACK*/
};


unsigned	RenderMode[] = {
		GL_POINT,	/*POINT*/
		GL_LINE,	/*LINE*/
		GL_FILL 	/*FILL*/
};


unsigned	DataType[] = {
		GL_BYTE,	/*BYTE*/
		GL_UNSIGNED_BYTE,	/*UNSIGNED_BYTE*/
		GL_SHORT,	/*SHORT*/
		GL_UNSIGNED_SHORT,	/*UNSIGNED_SHORT*/
		GL_INT,	/*INT*/
		GL_UNSIGNED_INT,	/*UNSIGNED_INT*/
		GL_FLOAT,	/*FLOAT*/
		GL_DOUBLE 	/*DOUBLE*/
};


unsigned	ClientState[] = {
		GL_INDEX_ARRAY,	/*COLOR_INDEX_ARRAY*/
		GL_VERTEX_ARRAY,	/*VERTEX_ARRAY*/
		GL_NORMAL_ARRAY,	/*NORMAL_ARRAY*/
		GL_COLOR_ARRAY,	/*COLOR_ARRAY*/
		GL_FOG_COORDINATE_ARRAY_EXT 	/*FOG_COORD_ARRAY*/
};


unsigned	TestFunction[] = {
		GL_NEVER,	/*NEVER*/
		GL_LESS,	/*LESS*/
		GL_GREATER,	/*GREATER*/
		GL_EQUAL,	/*EQUAL*/
		GL_GEQUAL,	/*GREATER_EQUAL*/
		GL_LEQUAL,	/*LESS_EQUAL*/
		GL_NOTEQUAL,	/*NOT_EQUAL*/
		GL_ALWAYS
};


unsigned	StencilOp[] = {
		GL_KEEP,	/*KEEP*/
		GL_ZERO,	/*ZERO*/
		GL_REPLACE,	/*REPLACE*/
		GL_INCR,	/*INCREMENT*/
		GL_DECR,	/*DECREMENT*/
		GL_INVERT 	/*INVERT*/
};


unsigned	AlphaFunction[] = {
		GL_ZERO,	/*ZERO*/
		GL_ONE,	/*ONE*/
		GL_DST_COLOR,	/*DST_COLOR*/
		GL_ONE_MINUS_DST_COLOR,	/*ONE_MINUS_DST_COLOR*/
		GL_DST_ALPHA,	/*DST_ALPHA*/
		GL_ONE_MINUS_DST_ALPHA,	/*ONE_MINUS_DST_ALPHA*/
		GL_SRC_COLOR,	/*SRC_COLOR*/
		GL_ONE_MINUS_SRC_COLOR,	/*ONE_MINUS_SRC_COLOR*/
		GL_SRC_ALPHA,	/*SRC_ALPHA*/
		GL_ONE_MINUS_SRC_ALPHA,	/*ONE_MINUS_SRC_ALPHA*/
		GL_SRC_ALPHA_SATURATE 	/*SRC_ALPHA_SATURATE*/
};


unsigned	FogFunction[] = {
		GL_LINEAR,	/*LINEAR*/
		GL_EXP,	/*EXP*/
		GL_EXP2 	/*EXP2*/
};


unsigned	FramebufferAttachment[] = {
		GL_COLOR_ATTACHMENT0_EXT,	/*COLOR_ATTACHMENT0*/
		GL_COLOR_ATTACHMENT1_EXT,	/*COLOR_ATTACHMENT1*/
		GL_COLOR_ATTACHMENT2_EXT,	/*COLOR_ATTACHMENT2*/
		GL_COLOR_ATTACHMENT3_EXT,	/*COLOR_ATTACHMENT3*/
		GL_COLOR_ATTACHMENT4_EXT,	/*COLOR_ATTACHMENT4*/
		GL_COLOR_ATTACHMENT5_EXT,	/*COLOR_ATTACHMENT5*/
		GL_COLOR_ATTACHMENT6_EXT,	/*COLOR_ATTACHMENT6*/
		GL_COLOR_ATTACHMENT7_EXT,	/*COLOR_ATTACHMENT7*/
		GL_COLOR_ATTACHMENT8_EXT,	/*COLOR_ATTACHMENT8*/
		GL_COLOR_ATTACHMENT9_EXT,	/*COLOR_ATTACHMENT9*/
		GL_COLOR_ATTACHMENT10_EXT,	/*COLOR_ATTACHMENT10*/
		GL_COLOR_ATTACHMENT11_EXT,	/*COLOR_ATTACHMENT11*/
		GL_COLOR_ATTACHMENT12_EXT,	/*COLOR_ATTACHMENT12*/
		GL_COLOR_ATTACHMENT13_EXT,	/*COLOR_ATTACHMENT13*/
		GL_COLOR_ATTACHMENT14_EXT,	/*COLOR_ATTACHMENT14*/
		GL_COLOR_ATTACHMENT15_EXT,	/*COLOR_ATTACHMENT15*/
		GL_DEPTH_ATTACHMENT_EXT,	/*DEPTH_ATTACHMENT*/
		GL_STENCIL_ATTACHMENT_EXT 	/*STENCIL_ATTACHMENT*/
};


unsigned	FramebufferStatus[] = {
		GL_FRAMEBUFFER_COMPLETE_EXT,	/*FRAMEBUFFER_COMPLETE*/
		GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_EXT,	/*FRAMEBUFFER_INCOMPLETE_ATTACHMENT*/
		GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT_EXT,	/*FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT*/
		GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_EXT,	/*FRAMEBUFFER_INCOMPLETE_DIMENSIONS*/
		GL_FRAMEBUFFER_INCOMPLETE_FORMATS_EXT,	/*FRAMEBUFFER_INCOMPLETE_FORMATS*/
		GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER_EXT,	/*FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER*/
		GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER_EXT,	/*FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER*/
		GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER_EXT	/*FRAMEBUFFER_UNSUPPORTED*/
};


unsigned	ShaderType[] = {
		GL_VERTEX_SHADER_ARB,	/*VERTEX*/
		GL_GEOMETRY_SHADER_EXT,	/*GEOMETRY*/
		GL_FRAGMENT_SHADER_ARB	/*FRAGMENT*/
};

//Additional render specific tables

unsigned 	TexGenSwitchEnum[] = {
		GL_TEXTURE_GEN_S,
		GL_TEXTURE_GEN_T,
		GL_TEXTURE_GEN_R,
		GL_TEXTURE_GEN_Q
};

unsigned	GetVBOBinding[] = {
		GL_ARRAY_BUFFER_BINDING_ARB,	/*VERTEX*/
		GL_ELEMENT_ARRAY_BUFFER_BINDING_ARB,	/*INDEX*/
		GL_PIXEL_PACK_BUFFER_BINDING_ARB,	/*R2VB*/
		GL_PIXEL_UNPACK_BUFFER_BINDING_ARB 	/*TEXTURE*/
};

unsigned	TextureStorageSize[] = {
		sizeof(GLubyte),	/*UNSIGNED_BYTE*/
		sizeof(GLbyte),	/*BYTE*/
		sizeof(GLushort),	/*UNSIGNED_SHORT*/
		sizeof(GLshort),	/*SHORT*/
		sizeof(GLuint),	/*UNSIGNED_INT*/
		sizeof(GLint),	/*INT*/
		sizeof(GLfloat) 	/*FLOAT*/
};

unsigned	DataTypeSize[] = {
		sizeof(GLbyte),	/*BYTE*/
		sizeof(GLubyte),	/*UNSIGNED_BYTE*/
		sizeof(GLshort),	/*SHORT*/
		sizeof(GLushort),	/*UNSIGNED_SHORT*/
		sizeof(GLint),	/*INT*/
		sizeof(GLuint),	/*UNSIGNED_INT*/
		sizeof(GLfloat),	/*FLOAT*/
		sizeof(GLdouble) 	/*DOUBLE*/
};

unsigned   FrontFace[] = {
		GL_CW,
		GL_CCW
};
//Namespaces end
}
}
}
}
