// forbid.gr.gen.h
// *** DO NOT EDIT BY HAND ***
// automatically generated by elkhound, from forbid.gr

#ifndef FORBID_GR_GEN_H
#define FORBID_GR_GEN_H

#include "useract.h"     // UserActions


// parser context class
class 
#line 9 "forbid.gr"
 Forbid : public UserActions {
public:

#line 18 "forbid.gr.gen.h"


private:
  USER_ACTION_FUNCTIONS      // see useract.h

  // declare the actual action function
  static SemanticValue doReductionAction(
    Forbid *ths,
    int productionId, SemanticValue const *semanticValues,
  SourceLoc loc,
  SourceLoc endloc);

  // declare the classifier function
  static int reclassifyToken(
    Forbid *ths,
    int oldTokenType, SemanticValue sval);

  void action0___EarlyStartSymbol(SourceLoc loc, SourceLoc endloc, SemanticValue top);
  void action1_Start(SourceLoc loc, SourceLoc endloc);
  void action2_TopA(SourceLoc loc, SourceLoc endloc);
  void action3_TopA(SourceLoc loc, SourceLoc endloc);
  void action4_A(SourceLoc loc, SourceLoc endloc);
  void action5_A(SourceLoc loc, SourceLoc endloc);

// the function which makes the parse tables
public:
  virtual ParseTables *makeTables();
};

#endif // FORBID_GR_GEN_H
