  //  Xml tokens for basic serialization

  //  a list element
  XTOK__List_Item, // "_List_Item"
  XTOK_item, // "item"

  //  a name-map element
  XTOK__NameMap_Item, // "_NameMap_Item"
  XTOK_name, // "name"
  // redundant token: item

  //  a map element
  XTOK__Map_Item, // "_Map_Item"
  XTOK_key, // "key"
  // redundant token: item

  //  NOTE: off for now
  //  an bidirectional unsatisfied link
  //  __Link
  //  from
  //  to
  //  Xml tokens for serializing file metadata nodes

  //  File nodes
  XTOK_File, // "File"
  // redundant token: name
  XTOK_numChars, // "numChars"
  XTOK_numLines, // "numLines"
  XTOK_lineLengths, // "lineLengths"
  XTOK_LineLengths, // "LineLengths"
  XTOK_hashLines, // "hashLines"
  XTOK_HashLineMap, // "HashLineMap"
  XTOK_ppFname, // "ppFname"
  XTOK_List_HashLineMap_directives, // "List_HashLineMap_directives"
  XTOK_directives, // "directives"
  XTOK_HashLine, // "HashLine"
  XTOK_ppLine, // "ppLine"
  XTOK_origLine, // "origLine"
  XTOK_origFname, // "origFname"
  XTOK_size, // "size"

  //  Some containers; I no longer care about order
  //    ObjList
  XTOK_List_files, // "List_files"

  //  FIX: are these in File or somewhere else?
  XTOK_loc, // "loc"
  XTOK_curLoc, // "curLoc"
  //  Xml tokens for serializing typesystem nodes

  //  Type nodes
  XTOK_Type, // "Type"
  XTOK_CVAtomicType, // "CVAtomicType"
  XTOK_PointerType, // "PointerType"
  XTOK_ReferenceType, // "ReferenceType"
  XTOK_FunctionType, // "FunctionType"
  XTOK_FunctionType_ExnSpec, // "FunctionType_ExnSpec"
  XTOK_ArrayType, // "ArrayType"
  XTOK_PointerToMemberType, // "PointerToMemberType"
  XTOK_DependentSizedArrayType, // "DependentSizedArrayType"
  //  fields
  XTOK_atomic, // "atomic"
  XTOK_atType, // "atType"
  XTOK_retType, // "retType"
  XTOK_eltType, // "eltType"
  XTOK_inClassNAT, // "inClassNAT"
  XTOK_cv, // "cv"
  // redundant token: size
  XTOK_sizeExpr, // "sizeExpr"

  //  AtomicType nodes
  XTOK_AtomicType, // "AtomicType"
  XTOK_NamedAtomicType, // "NamedAtomicType"
  XTOK_SimpleType, // "SimpleType"
  XTOK_CompoundType, // "CompoundType"
  XTOK_EnumType, // "EnumType"
  XTOK_EnumType_Value, // "EnumType_Value"
  XTOK_TypeVariable, // "TypeVariable"
  XTOK_PseudoInstantiation, // "PseudoInstantiation"
  XTOK_DependentQType, // "DependentQType"
  //  more fields
  XTOK_typedefVar, // "typedefVar"
  XTOK_forward, // "forward"
  XTOK_dataMembers, // "dataMembers"
  XTOK_virtualBases, // "virtualBases"
  XTOK_subobj, // "subobj"
  XTOK_conversionOperators, // "conversionOperators"
  XTOK_instName, // "instName"
  XTOK_syntax, // "syntax"
  XTOK_parameterizingScope, // "parameterizingScope"
  XTOK_selfType, // "selfType"
  XTOK_valueIndex, // "valueIndex"
  XTOK_nextValue, // "nextValue"
  XTOK_hasNegativeValues, // "hasNegativeValues"
  XTOK_primary, // "primary"
  XTOK_first, // "first"
  // redundant token: name
  XTOK_access, // "access"
  XTOK_type, // "type"
  XTOK_bases, // "bases"
  XTOK_args, // "args"
  XTOK_rest, // "rest"
  XTOK_fullyQualifiedMangledName, // "fullyQualifiedMangledName"

  //  Other
  XTOK_Variable, // "Variable"
  XTOK_Scope, // "Scope"
  XTOK_BaseClass, // "BaseClass"
  XTOK_BaseClassSubobj, // "BaseClassSubobj"
  XTOK_OverloadSet, // "OverloadSet"
  XTOK_STemplateArgument, // "STemplateArgument"
  XTOK_TemplateInfo, // "TemplateInfo"
  XTOK_InheritedTemplateParams, // "InheritedTemplateParams"
  //  yet more fields
  XTOK_flags, // "flags"
  XTOK_value, // "value"
  XTOK_defaultParamType, // "defaultParamType"
  XTOK_funcDefn, // "funcDefn"
  XTOK_scope, // "scope"
  //  should no longer be using this: intData
  XTOK_real, // "real"
  XTOK_maybeUsedAsAlias, // "maybeUsedAsAlias"
  XTOK_user1, // "user1"
  XTOK_user2, // "user2"
  XTOK_usingAlias_or_parameterizedEntity, // "usingAlias_or_parameterizedEntity"
  XTOK_templInfo, // "templInfo"
  XTOK_canAcceptNames, // "canAcceptNames"
  XTOK_parentScope, // "parentScope"
  XTOK_scopeKind, // "scopeKind"
  XTOK_hasValue, // "hasValue"
  XTOK_namespaceVar, // "namespaceVar"
  XTOK_curCompound, // "curCompound"
  XTOK_ct, // "ct"
  XTOK_variables, // "variables"
  XTOK_typeTags, // "typeTags"
  XTOK_parents, // "parents"
  XTOK_templateParams, // "templateParams"
  XTOK_overload, // "overload"
  XTOK_set, // "set"
  XTOK_inheritedParams, // "inheritedParams"
  XTOK_instantiationOf, // "instantiationOf"
  XTOK_instantiations, // "instantiations"
  XTOK_specializationOf, // "specializationOf"
  XTOK_specializations, // "specializations"
  XTOK_arguments, // "arguments"
  XTOK_partialInstantiationOf, // "partialInstantiationOf"
  XTOK_partialInstantiations, // "partialInstantiations"
  XTOK_argumentsToPrimary, // "argumentsToPrimary"
  XTOK_defnScope, // "defnScope"
  XTOK_definitionTemplateInfo, // "definitionTemplateInfo"
  XTOK_enclosing, // "enclosing"
  XTOK_instLoc, // "instLoc"
  //  params
  XTOK_kind, // "kind"
  XTOK_t, // "t"
  XTOK_i, // "i"
  XTOK_v, // "v"
  XTOK_e, // "e"
  XTOK_at, // "at"
  XTOK_parameterOrdinal, // "parameterOrdinal"

  //  Some containers; I no longer care about order
  //    ObjList
  XTOK_List_CompoundType_bases, // "List_CompoundType_bases"
  XTOK_List_CompoundType_virtualBases, // "List_CompoundType_virtualBases"
  XTOK_List_PseudoInstantiation_args, // "List_PseudoInstantiation_args"
  XTOK_List_TemplateInfo_inheritedParams, // "List_TemplateInfo_inheritedParams"
  XTOK_List_TemplateInfo_arguments, // "List_TemplateInfo_arguments"
  XTOK_List_TemplateInfo_argumentsToPrimary, // "List_TemplateInfo_argumentsToPrimary"
  XTOK_List_PQ_qualifier_sargs, // "List_PQ_qualifier_sargs"
  XTOK_List_PQ_template_sargs, // "List_PQ_template_sargs"
  //    SObjList
  XTOK_List_FunctionType_params, // "List_FunctionType_params"
  XTOK_List_CompoundType_dataMembers, // "List_CompoundType_dataMembers"
  XTOK_List_CompoundType_conversionOperators, // "List_CompoundType_conversionOperators"
  XTOK_List_BaseClassSubobj_parents, // "List_BaseClassSubobj_parents"
  XTOK_List_ExnSpec_types, // "List_ExnSpec_types"
  XTOK_List_Scope_templateParams, // "List_Scope_templateParams"
  XTOK_List_OverloadSet_set, // "List_OverloadSet_set"
  XTOK_List_TemplateInfo_instantiations, // "List_TemplateInfo_instantiations"
  XTOK_List_TemplateInfo_specializations, // "List_TemplateInfo_specializations"
  XTOK_List_TemplateInfo_partialInstantiations, // "List_TemplateInfo_partialInstantiations"
  XTOK_List_TemplateParams_params, // "List_TemplateParams_params"

  //    StringRefMap
  XTOK_NameMap_Scope_variables, // "NameMap_Scope_variables"
  XTOK_NameMap_Scope_typeTags, // "NameMap_Scope_typeTags"
  XTOK_NameMap_EnumType_valueIndex, // "NameMap_EnumType_valueIndex"
  //  Xml tokens for serializing Ast nodes
  XTOK_TranslationUnit, // "TranslationUnit"
  XTOK_TopForm, // "TopForm"
  XTOK_TF_decl, // "TF_decl"
  XTOK_TF_func, // "TF_func"
  XTOK_TF_template, // "TF_template"
  XTOK_TF_explicitInst, // "TF_explicitInst"
  XTOK_TF_linkage, // "TF_linkage"
  XTOK_TF_one_linkage, // "TF_one_linkage"
  XTOK_TF_asm, // "TF_asm"
  XTOK_TF_namespaceDefn, // "TF_namespaceDefn"
  XTOK_TF_namespaceDecl, // "TF_namespaceDecl"
  XTOK_Function, // "Function"
  XTOK_MemberInit, // "MemberInit"
  XTOK_Declaration, // "Declaration"
  XTOK_ASTTypeId, // "ASTTypeId"
  XTOK_PQName, // "PQName"
  XTOK_PQ_qualifier, // "PQ_qualifier"
  XTOK_PQ_name, // "PQ_name"
  XTOK_PQ_operator, // "PQ_operator"
  XTOK_PQ_template, // "PQ_template"
  XTOK_PQ_variable, // "PQ_variable"
  XTOK_TypeSpecifier, // "TypeSpecifier"
  XTOK_TS_name, // "TS_name"
  XTOK_TS_simple, // "TS_simple"
  XTOK_TS_elaborated, // "TS_elaborated"
  XTOK_TS_classSpec, // "TS_classSpec"
  XTOK_TS_enumSpec, // "TS_enumSpec"
  XTOK_TS_type, // "TS_type"
  XTOK_TS_typeof, // "TS_typeof"
  XTOK_BaseClassSpec, // "BaseClassSpec"
  XTOK_Enumerator, // "Enumerator"
  XTOK_MemberList, // "MemberList"
  XTOK_Member, // "Member"
  XTOK_MR_decl, // "MR_decl"
  XTOK_MR_func, // "MR_func"
  XTOK_MR_access, // "MR_access"
  XTOK_MR_usingDecl, // "MR_usingDecl"
  XTOK_MR_template, // "MR_template"
  XTOK_Declarator, // "Declarator"
  XTOK_IDeclarator, // "IDeclarator"
  XTOK_D_name, // "D_name"
  XTOK_D_pointer, // "D_pointer"
  XTOK_D_reference, // "D_reference"
  XTOK_D_func, // "D_func"
  XTOK_D_array, // "D_array"
  XTOK_D_bitfield, // "D_bitfield"
  XTOK_D_ptrToMember, // "D_ptrToMember"
  XTOK_D_grouping, // "D_grouping"
  XTOK_ExceptionSpec, // "ExceptionSpec"
  XTOK_OperatorName, // "OperatorName"
  XTOK_ON_newDel, // "ON_newDel"
  XTOK_ON_operator, // "ON_operator"
  XTOK_ON_conversion, // "ON_conversion"
  XTOK_Statement, // "Statement"
  XTOK_S_skip, // "S_skip"
  XTOK_S_label, // "S_label"
  XTOK_S_case, // "S_case"
  XTOK_S_default, // "S_default"
  XTOK_S_expr, // "S_expr"
  XTOK_S_compound, // "S_compound"
  XTOK_S_if, // "S_if"
  XTOK_S_switch, // "S_switch"
  XTOK_S_while, // "S_while"
  XTOK_S_doWhile, // "S_doWhile"
  XTOK_S_for, // "S_for"
  XTOK_S_break, // "S_break"
  XTOK_S_continue, // "S_continue"
  XTOK_S_return, // "S_return"
  XTOK_S_goto, // "S_goto"
  XTOK_S_decl, // "S_decl"
  XTOK_S_try, // "S_try"
  XTOK_S_asm, // "S_asm"
  XTOK_S_namespaceDecl, // "S_namespaceDecl"
  XTOK_S_function, // "S_function"
  XTOK_S_rangeCase, // "S_rangeCase"
  XTOK_S_computedGoto, // "S_computedGoto"
  XTOK_Condition, // "Condition"
  XTOK_CN_expr, // "CN_expr"
  XTOK_CN_decl, // "CN_decl"
  XTOK_Handler, // "Handler"
  XTOK_Expression, // "Expression"
  XTOK_E_boolLit, // "E_boolLit"
  XTOK_E_intLit, // "E_intLit"
  XTOK_E_floatLit, // "E_floatLit"
  XTOK_E_stringLit, // "E_stringLit"
  XTOK_E_charLit, // "E_charLit"
  XTOK_E_this, // "E_this"
  XTOK_E_variable, // "E_variable"
  XTOK_E_funCall, // "E_funCall"
  XTOK_E_constructor, // "E_constructor"
  XTOK_E_fieldAcc, // "E_fieldAcc"
  XTOK_E_sizeof, // "E_sizeof"
  XTOK_E_unary, // "E_unary"
  XTOK_E_effect, // "E_effect"
  XTOK_E_binary, // "E_binary"
  XTOK_E_addrOf, // "E_addrOf"
  XTOK_E_deref, // "E_deref"
  XTOK_E_cast, // "E_cast"
  XTOK_E_cond, // "E_cond"
  XTOK_E_sizeofType, // "E_sizeofType"
  XTOK_E_assign, // "E_assign"
  XTOK_E_new, // "E_new"
  XTOK_E_delete, // "E_delete"
  XTOK_E_throw, // "E_throw"
  XTOK_E_keywordCast, // "E_keywordCast"
  XTOK_E_typeidExpr, // "E_typeidExpr"
  XTOK_E_typeidType, // "E_typeidType"
  XTOK_E_grouping, // "E_grouping"
  XTOK_E_arrow, // "E_arrow"
  XTOK_E_statement, // "E_statement"
  XTOK_E_compoundLit, // "E_compoundLit"
  XTOK_E___builtin_constant_p, // "E___builtin_constant_p"
  XTOK_E___builtin_va_arg, // "E___builtin_va_arg"
  XTOK_E_alignofType, // "E_alignofType"
  XTOK_E_alignofExpr, // "E_alignofExpr"
  XTOK_E_gnuCond, // "E_gnuCond"
  XTOK_E_addrOfLabel, // "E_addrOfLabel"
  XTOK_FullExpression, // "FullExpression"
  XTOK_ArgExpression, // "ArgExpression"
  XTOK_ArgExpressionListOpt, // "ArgExpressionListOpt"
  XTOK_Initializer, // "Initializer"
  XTOK_IN_expr, // "IN_expr"
  XTOK_IN_compound, // "IN_compound"
  XTOK_IN_ctor, // "IN_ctor"
  XTOK_IN_designated, // "IN_designated"
  XTOK_TemplateDeclaration, // "TemplateDeclaration"
  XTOK_TD_func, // "TD_func"
  XTOK_TD_decl, // "TD_decl"
  XTOK_TD_tmember, // "TD_tmember"
  XTOK_TemplateParameter, // "TemplateParameter"
  XTOK_TP_type, // "TP_type"
  XTOK_TP_nontype, // "TP_nontype"
  XTOK_TP_template, // "TP_template"
  XTOK_TemplateArgument, // "TemplateArgument"
  XTOK_TA_type, // "TA_type"
  XTOK_TA_nontype, // "TA_nontype"
  XTOK_TA_templateUsed, // "TA_templateUsed"
  XTOK_NamespaceDecl, // "NamespaceDecl"
  XTOK_ND_alias, // "ND_alias"
  XTOK_ND_usingDecl, // "ND_usingDecl"
  XTOK_ND_usingDir, // "ND_usingDir"
  XTOK_FullExpressionAnnot, // "FullExpressionAnnot"
  XTOK_ASTTypeof, // "ASTTypeof"
  XTOK_TS_typeof_expr, // "TS_typeof_expr"
  XTOK_TS_typeof_type, // "TS_typeof_type"
  XTOK_Designator, // "Designator"
  XTOK_FieldDesignator, // "FieldDesignator"
  XTOK_SubscriptDesignator, // "SubscriptDesignator"
  XTOK_AttributeSpecifierList, // "AttributeSpecifierList"
  XTOK_AttributeSpecifier, // "AttributeSpecifier"
  XTOK_Attribute, // "Attribute"
  XTOK_AT_empty, // "AT_empty"
  XTOK_AT_word, // "AT_word"
  XTOK_AT_func, // "AT_func"

  //  List 'classes'
  XTOK_List_TF_namespaceDefn_forms, // "List_TF_namespaceDefn_forms"
  XTOK_List_TranslationUnit_topForms, // "List_TranslationUnit_topForms"
  XTOK_List_Function_inits, // "List_Function_inits"
  XTOK_List_Function_handlers, // "List_Function_handlers"
  XTOK_List_MemberInit_args, // "List_MemberInit_args"
  XTOK_List_MemberList_list, // "List_MemberList_list"
  XTOK_List_Declaration_decllist, // "List_Declaration_decllist"
  XTOK_List_TS_classSpec_bases, // "List_TS_classSpec_bases"
  XTOK_List_TS_enumSpec_elts, // "List_TS_enumSpec_elts"
  XTOK_List_D_func_params, // "List_D_func_params"
  XTOK_List_D_func_kAndR_params, // "List_D_func_kAndR_params"
  XTOK_List_S_try_handlers, // "List_S_try_handlers"
  XTOK_List_ExceptionSpec_types, // "List_ExceptionSpec_types"
  XTOK_List_S_compound_stmts, // "List_S_compound_stmts"
  XTOK_List_E_funCall_args, // "List_E_funCall_args"
  XTOK_List_E_constructor_args, // "List_E_constructor_args"
  XTOK_List_E_new_placementArgs, // "List_E_new_placementArgs"
  XTOK_List_ArgExpressionListOpt_list, // "List_ArgExpressionListOpt_list"
  XTOK_List_IN_compound_inits, // "List_IN_compound_inits"
  XTOK_List_IN_ctor_args, // "List_IN_ctor_args"
  XTOK_List_TP_template_parameters, // "List_TP_template_parameters"
  XTOK_List_IN_designated_designator_list, // "List_IN_designated_designator_list"
  XTOK_List_FullExpressionAnnot_declarations, // "List_FullExpressionAnnot_declarations"
  XTOK_List_AT_func_args, // "List_AT_func_args"

  //  child attribute names
  // redundant token: access
  XTOK_after, // "after"
  XTOK_alias, // "alias"
  XTOK_alignment, // "alignment"
  XTOK_annot, // "annot"
  // redundant token: args
  XTOK_array, // "array"
  XTOK_arraySize, // "arraySize"
  XTOK_artificial, // "artificial"
  XTOK_attr, // "attr"
  XTOK_atype, // "atype"
  XTOK_b, // "b"
  XTOK_base, // "base"
  // redundant token: bases
  XTOK_bits, // "bits"
  XTOK_body, // "body"
  XTOK_branches, // "branches"
  XTOK_c, // "c"
  XTOK_colonColon, // "colonColon"
  XTOK_cond, // "cond"
  XTOK_context, // "context"
  XTOK_continuation, // "continuation"
  XTOK_ctorArgs, // "ctorArgs"
  XTOK_ctorStatement, // "ctorStatement"
  XTOK_ctorVar, // "ctorVar"
  XTOK_ctype, // "ctype"
  // redundant token: cv
  XTOK_d, // "d"
  XTOK_decl, // "decl"
  XTOK_declarations, // "declarations"
  XTOK_decllist, // "decllist"
  XTOK_defaultTemplate, // "defaultTemplate"
  XTOK_defaultType, // "defaultType"
  XTOK_designator_list, // "designator_list"
  XTOK_dflags, // "dflags"
  XTOK_dtorStatement, // "dtorStatement"
  // redundant token: e
  XTOK_e1, // "e1"
  XTOK_e2, // "e2"
  XTOK_el, // "el"
  XTOK_elseBranch, // "elseBranch"
  XTOK_elts, // "elts"
  XTOK_endloc, // "endloc"
  XTOK_enumValue, // "enumValue"
  XTOK_etype, // "etype"
  XTOK_exnSpec, // "exnSpec"
  XTOK_expr, // "expr"
  XTOK_exprHi, // "exprHi"
  XTOK_exprLo, // "exprLo"
  XTOK_f, // "f"
  XTOK_fakeName, // "fakeName"
  XTOK_field, // "field"
  XTOK_fieldName, // "fieldName"
  XTOK_form, // "form"
  XTOK_forms, // "forms"
  XTOK_fullTextNQ, // "fullTextNQ"
  XTOK_func, // "func"
  XTOK_funcType, // "funcType"
  XTOK_globalCtorStatement, // "globalCtorStatement"
  XTOK_globalDtorStatement, // "globalDtorStatement"
  XTOK_globalScope, // "globalScope"
  XTOK_globalVar, // "globalVar"
  XTOK_handlers, // "handlers"
  XTOK_heapVar, // "heapVar"
  // redundant token: i
  XTOK_id, // "id"
  XTOK_idx_computed, // "idx_computed"
  XTOK_idx_computed2, // "idx_computed2"
  XTOK_idx_expr, // "idx_expr"
  XTOK_idx_expr2, // "idx_expr2"
  XTOK_implicitlyDefined, // "implicitlyDefined"
  XTOK_init, // "init"
  XTOK_inits, // "inits"
  XTOK_instFlags, // "instFlags"
  XTOK_isArray, // "isArray"
  XTOK_isMember, // "isMember"
  XTOK_isNew, // "isNew"
  XTOK_isNewSize, // "isNewSize"
  XTOK_isVirtual, // "isVirtual"
  XTOK_k, // "k"
  XTOK_kAndR_params, // "kAndR_params"
  // redundant token: key
  XTOK_keyword, // "keyword"
  XTOK_labelName, // "labelName"
  XTOK_labelVal, // "labelVal"
  XTOK_labelValHi, // "labelValHi"
  XTOK_labelValLo, // "labelValLo"
  XTOK_linkageType, // "linkageType"
  XTOK_list, // "list"
  // redundant token: loc
  XTOK_localArg, // "localArg"
  XTOK_member, // "member"
  XTOK_members, // "members"
  // redundant token: name
  XTOK_nameAndParams, // "nameAndParams"
  XTOK_nestedName, // "nestedName"
  XTOK_next, // "next"
  XTOK_nondependentVar, // "nondependentVar"
  XTOK_numBits, // "numBits"
  XTOK_o, // "o"
  XTOK_obj, // "obj"
  XTOK_op, // "op"
  XTOK_original, // "original"
  XTOK_param, // "param"
  XTOK_parameters, // "parameters"
  XTOK_params, // "params"
  XTOK_placementArgs, // "placementArgs"
  XTOK_ptr, // "ptr"
  XTOK_qualifier, // "qualifier"
  XTOK_qualifierVar, // "qualifierVar"
  XTOK_receiver, // "receiver"
  // redundant token: rest
  XTOK_retObj, // "retObj"
  XTOK_retVar, // "retVar"
  XTOK_retspec, // "retspec"
  XTOK_s, // "s"
  XTOK_sargs, // "sargs"
  // redundant token: size
  XTOK_spec, // "spec"
  XTOK_src, // "src"
  XTOK_stmts, // "stmts"
  XTOK_stype, // "stype"
  XTOK_target, // "target"
  XTOK_tchecked, // "tchecked"
  XTOK_tcheckedType, // "tcheckedType"
  XTOK_td, // "td"
  XTOK_templArgs, // "templArgs"
  XTOK_text, // "text"
  XTOK_th, // "th"
  XTOK_thenBranch, // "thenBranch"
  XTOK_topForms, // "topForms"
  XTOK_ttype, // "ttype"
  // redundant token: type
  XTOK_typeId, // "typeId"
  XTOK_typenameUsed, // "typenameUsed"
  XTOK_types, // "types"
  XTOK_var, // "var"
  XTOK_w, // "w"
  XTOK_was_IN_expr, // "was_IN_expr"
