
extern const char* NODE_NAMES [];

const char* NODE_NAMES [] = {
	"UNKNOWN",
	"NAMESPACE",
	"FUNCTION",
	"TEMPLATE_FUNCTION",
	"CLASS",
	"TEMPLATE_CLASS",
	"CLASS_CONSTRUCTOR",
	"CLASS_COPY_CONSTRUCTOR",
	"CLASS_DESTRUCTOR",
	"CLASS_METHOD",
	"CLASS_PROPERTY",
	"CLASS_FIELD",
	"ENUM",
	"ENUM_VALUE",
	"CONSTANT",
	"GLOBAL_VARIABLE",
	"TYPEDEF",
	"TEMPLATE_SPECIALIZATION",
	"STL_SPECIALIZATION"
};
