//This test the correnctness of STL parsing
#include <algorithm>
#include <array>
#include <assert.h>
#include <atomic>
#include <bitset>
#include <cassert>
#include <ccomplex>
#include <cctype>
#include <cerrno>
#include <cfenv>
#include <cfloat>
#include <chrono>
#include <cinttypes>
#include <ciso646>
#include <climits>
#include <clocale>
#include <cmath>
#include <codecvt>
#include <complex>
#include <complex.h>
#include <condition_variable>
#include <csetjmp>
#include <csignal>
#include <cstdarg>
#include <cstdbool>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctgmath>
#include <ctime>
#include <ctype.h>
#include <cwchar>
#include <cwctype>
#include <deque>
#include <errno.h>
#include <exception>
#include <fcntl.h>
#include <float.h>
#include <forward_list>
#include <fstream>
#include <functional>
#include <future>
#include <initializer_list>
#include <inttypes.h>
#include <iomanip>
#include <ios>
#include <iosfwd>
#include <iostream>
#include <istream>
#include <iterator>
#include <limits>
#include <limits.h>
#include <list>
#include <locale>
#include <locale.h>
#include <malloc.h>
#include <map>
#include <math.h>
#include <memory>
#include <mutex>
#include <new>
#include <numeric>
#include <ostream>
#include <pthread.h>
#include <queue>
#include <random>
#include <ratio>
#include <regex>
#include <regex.h>
#include <scoped_allocator>
#include <search.h>
#include <set>
#include <setjmp.h>
#include <signal.h>
#include <sstream>
#include <stack>
#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdexcept>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <streambuf>
#include <string>
#include <string.h>
#include <strstream>
#include <system_error>
#include <tar.h>
#include <termios.h>
#include <tgmath.h>
#include <thread>
#include <time.h>
#include <tuple>
#include <typeindex>
#include <typeinfo>
#include <type_traits>
#include <unistd.h>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <utime.h>
#include <valarray>
#include <vector>
#include <wchar.h>
#include <wctype.h>

typedef std::vector<int> int_vector;
typedef std::map< std::string, std::vector<size_t> > test_map;

namespace mine
{
using std::clog;
using std::cout;
}

