  //  Xml tokens for basic serialization

  //  a list element
  "XTOK__List_Item",
  "XTOK_item",

  //  a name-map element
  "XTOK__NameMap_Item",
  "XTOK_name",
  // redundant token: item

  //  a map element
  "XTOK__Map_Item",
  "XTOK_key",
  // redundant token: item

  //  NOTE: off for now
  //  an bidirectional unsatisfied link
  //  __Link
  //  from
  //  to
  //  Xml tokens for serializing file metadata nodes

  //  File nodes
  "XTOK_File",
  // redundant token: name
  "XTOK_numChars",
  "XTOK_numLines",
  "XTOK_lineLengths",
  "XTOK_LineLengths",
  "XTOK_hashLines",
  "XTOK_HashLineMap",
  "XTOK_ppFname",
  "XTOK_List_HashLineMap_directives",
  "XTOK_directives",
  "XTOK_HashLine",
  "XTOK_ppLine",
  "XTOK_origLine",
  "XTOK_origFname",
  "XTOK_size",

  //  Some containers; I no longer care about order
  //    ObjList
  "XTOK_List_files",

  //  FIX: are these in File or somewhere else?
  "XTOK_loc",
  "XTOK_curLoc",
  //  Xml tokens for serializing typesystem nodes

  //  Type nodes
  "XTOK_Type",
  "XTOK_CVAtomicType",
  "XTOK_PointerType",
  "XTOK_ReferenceType",
  "XTOK_FunctionType",
  "XTOK_FunctionType_ExnSpec",
  "XTOK_ArrayType",
  "XTOK_PointerToMemberType",
  "XTOK_DependentSizedArrayType",
  //  fields
  "XTOK_atomic",
  "XTOK_atType",
  "XTOK_retType",
  "XTOK_eltType",
  "XTOK_inClassNAT",
  "XTOK_cv",
  // redundant token: size
  "XTOK_sizeExpr",

  //  AtomicType nodes
  "XTOK_AtomicType",
  "XTOK_NamedAtomicType",
  "XTOK_SimpleType",
  "XTOK_CompoundType",
  "XTOK_EnumType",
  "XTOK_EnumType_Value",
  "XTOK_TypeVariable",
  "XTOK_PseudoInstantiation",
  "XTOK_DependentQType",
  //  more fields
  "XTOK_typedefVar",
  "XTOK_forward",
  "XTOK_dataMembers",
  "XTOK_virtualBases",
  "XTOK_subobj",
  "XTOK_conversionOperators",
  "XTOK_instName",
  "XTOK_syntax",
  "XTOK_parameterizingScope",
  "XTOK_selfType",
  "XTOK_valueIndex",
  "XTOK_nextValue",
  "XTOK_hasNegativeValues",
  "XTOK_primary",
  "XTOK_first",
  // redundant token: name
  "XTOK_access",
  "XTOK_type",
  "XTOK_bases",
  "XTOK_args",
  "XTOK_rest",
  "XTOK_fullyQualifiedMangledName",

  //  Other
  "XTOK_Variable",
  "XTOK_Scope",
  "XTOK_BaseClass",
  "XTOK_BaseClassSubobj",
  "XTOK_OverloadSet",
  "XTOK_STemplateArgument",
  "XTOK_TemplateInfo",
  "XTOK_InheritedTemplateParams",
  //  yet more fields
  "XTOK_flags",
  "XTOK_value",
  "XTOK_defaultParamType",
  "XTOK_funcDefn",
  "XTOK_scope",
  //  should no longer be using this: intData
  "XTOK_real",
  "XTOK_maybeUsedAsAlias",
  "XTOK_user1",
  "XTOK_user2",
  "XTOK_usingAlias_or_parameterizedEntity",
  "XTOK_templInfo",
  "XTOK_canAcceptNames",
  "XTOK_parentScope",
  "XTOK_scopeKind",
  "XTOK_hasValue",
  "XTOK_namespaceVar",
  "XTOK_curCompound",
  "XTOK_ct",
  "XTOK_variables",
  "XTOK_typeTags",
  "XTOK_parents",
  "XTOK_templateParams",
  "XTOK_overload",
  "XTOK_set",
  "XTOK_inheritedParams",
  "XTOK_instantiationOf",
  "XTOK_instantiations",
  "XTOK_specializationOf",
  "XTOK_specializations",
  "XTOK_arguments",
  "XTOK_partialInstantiationOf",
  "XTOK_partialInstantiations",
  "XTOK_argumentsToPrimary",
  "XTOK_defnScope",
  "XTOK_definitionTemplateInfo",
  "XTOK_enclosing",
  "XTOK_instLoc",
  //  params
  "XTOK_kind",
  "XTOK_t",
  "XTOK_i",
  "XTOK_v",
  "XTOK_e",
  "XTOK_at",
  "XTOK_parameterOrdinal",

  //  Some containers; I no longer care about order
  //    ObjList
  "XTOK_List_CompoundType_bases",
  "XTOK_List_CompoundType_virtualBases",
  "XTOK_List_PseudoInstantiation_args",
  "XTOK_List_TemplateInfo_inheritedParams",
  "XTOK_List_TemplateInfo_arguments",
  "XTOK_List_TemplateInfo_argumentsToPrimary",
  "XTOK_List_PQ_qualifier_sargs",
  "XTOK_List_PQ_template_sargs",
  //    SObjList
  "XTOK_List_FunctionType_params",
  "XTOK_List_CompoundType_dataMembers",
  "XTOK_List_CompoundType_conversionOperators",
  "XTOK_List_BaseClassSubobj_parents",
  "XTOK_List_ExnSpec_types",
  "XTOK_List_Scope_templateParams",
  "XTOK_List_OverloadSet_set",
  "XTOK_List_TemplateInfo_instantiations",
  "XTOK_List_TemplateInfo_specializations",
  "XTOK_List_TemplateInfo_partialInstantiations",
  "XTOK_List_TemplateParams_params",

  //    StringRefMap
  "XTOK_NameMap_Scope_variables",
  "XTOK_NameMap_Scope_typeTags",
  "XTOK_NameMap_EnumType_valueIndex",
  //  Xml tokens for serializing Ast nodes
  "XTOK_TranslationUnit",
  "XTOK_TopForm",
  "XTOK_TF_decl",
  "XTOK_TF_func",
  "XTOK_TF_template",
  "XTOK_TF_explicitInst",
  "XTOK_TF_linkage",
  "XTOK_TF_one_linkage",
  "XTOK_TF_asm",
  "XTOK_TF_namespaceDefn",
  "XTOK_TF_namespaceDecl",
  "XTOK_Function",
  "XTOK_MemberInit",
  "XTOK_Declaration",
  "XTOK_ASTTypeId",
  "XTOK_PQName",
  "XTOK_PQ_qualifier",
  "XTOK_PQ_name",
  "XTOK_PQ_operator",
  "XTOK_PQ_template",
  "XTOK_PQ_variable",
  "XTOK_TypeSpecifier",
  "XTOK_TS_name",
  "XTOK_TS_simple",
  "XTOK_TS_elaborated",
  "XTOK_TS_classSpec",
  "XTOK_TS_enumSpec",
  "XTOK_TS_type",
  "XTOK_TS_typeof",
  "XTOK_BaseClassSpec",
  "XTOK_Enumerator",
  "XTOK_MemberList",
  "XTOK_Member",
  "XTOK_MR_decl",
  "XTOK_MR_func",
  "XTOK_MR_access",
  "XTOK_MR_usingDecl",
  "XTOK_MR_template",
  "XTOK_Declarator",
  "XTOK_IDeclarator",
  "XTOK_D_name",
  "XTOK_D_pointer",
  "XTOK_D_reference",
  "XTOK_D_func",
  "XTOK_D_array",
  "XTOK_D_bitfield",
  "XTOK_D_ptrToMember",
  "XTOK_D_grouping",
  "XTOK_ExceptionSpec",
  "XTOK_OperatorName",
  "XTOK_ON_newDel",
  "XTOK_ON_operator",
  "XTOK_ON_conversion",
  "XTOK_Statement",
  "XTOK_S_skip",
  "XTOK_S_label",
  "XTOK_S_case",
  "XTOK_S_default",
  "XTOK_S_expr",
  "XTOK_S_compound",
  "XTOK_S_if",
  "XTOK_S_switch",
  "XTOK_S_while",
  "XTOK_S_doWhile",
  "XTOK_S_for",
  "XTOK_S_break",
  "XTOK_S_continue",
  "XTOK_S_return",
  "XTOK_S_goto",
  "XTOK_S_decl",
  "XTOK_S_try",
  "XTOK_S_asm",
  "XTOK_S_namespaceDecl",
  "XTOK_S_function",
  "XTOK_S_rangeCase",
  "XTOK_S_computedGoto",
  "XTOK_Condition",
  "XTOK_CN_expr",
  "XTOK_CN_decl",
  "XTOK_Handler",
  "XTOK_Expression",
  "XTOK_E_boolLit",
  "XTOK_E_intLit",
  "XTOK_E_floatLit",
  "XTOK_E_stringLit",
  "XTOK_E_charLit",
  "XTOK_E_this",
  "XTOK_E_variable",
  "XTOK_E_funCall",
  "XTOK_E_constructor",
  "XTOK_E_fieldAcc",
  "XTOK_E_sizeof",
  "XTOK_E_unary",
  "XTOK_E_effect",
  "XTOK_E_binary",
  "XTOK_E_addrOf",
  "XTOK_E_deref",
  "XTOK_E_cast",
  "XTOK_E_cond",
  "XTOK_E_sizeofType",
  "XTOK_E_assign",
  "XTOK_E_new",
  "XTOK_E_delete",
  "XTOK_E_throw",
  "XTOK_E_keywordCast",
  "XTOK_E_typeidExpr",
  "XTOK_E_typeidType",
  "XTOK_E_grouping",
  "XTOK_E_arrow",
  "XTOK_E_statement",
  "XTOK_E_compoundLit",
  "XTOK_E___builtin_constant_p",
  "XTOK_E___builtin_va_arg",
  "XTOK_E_alignofType",
  "XTOK_E_alignofExpr",
  "XTOK_E_gnuCond",
  "XTOK_E_addrOfLabel",
  "XTOK_FullExpression",
  "XTOK_ArgExpression",
  "XTOK_ArgExpressionListOpt",
  "XTOK_Initializer",
  "XTOK_IN_expr",
  "XTOK_IN_compound",
  "XTOK_IN_ctor",
  "XTOK_IN_designated",
  "XTOK_TemplateDeclaration",
  "XTOK_TD_func",
  "XTOK_TD_decl",
  "XTOK_TD_tmember",
  "XTOK_TemplateParameter",
  "XTOK_TP_type",
  "XTOK_TP_nontype",
  "XTOK_TP_template",
  "XTOK_TemplateArgument",
  "XTOK_TA_type",
  "XTOK_TA_nontype",
  "XTOK_TA_templateUsed",
  "XTOK_NamespaceDecl",
  "XTOK_ND_alias",
  "XTOK_ND_usingDecl",
  "XTOK_ND_usingDir",
  "XTOK_FullExpressionAnnot",
  "XTOK_ASTTypeof",
  "XTOK_TS_typeof_expr",
  "XTOK_TS_typeof_type",
  "XTOK_Designator",
  "XTOK_FieldDesignator",
  "XTOK_SubscriptDesignator",
  "XTOK_AttributeSpecifierList",
  "XTOK_AttributeSpecifier",
  "XTOK_Attribute",
  "XTOK_AT_empty",
  "XTOK_AT_word",
  "XTOK_AT_func",

  //  List 'classes'
  "XTOK_List_TF_namespaceDefn_forms",
  "XTOK_List_TranslationUnit_topForms",
  "XTOK_List_Function_inits",
  "XTOK_List_Function_handlers",
  "XTOK_List_MemberInit_args",
  "XTOK_List_MemberList_list",
  "XTOK_List_Declaration_decllist",
  "XTOK_List_TS_classSpec_bases",
  "XTOK_List_TS_enumSpec_elts",
  "XTOK_List_D_func_params",
  "XTOK_List_D_func_kAndR_params",
  "XTOK_List_S_try_handlers",
  "XTOK_List_ExceptionSpec_types",
  "XTOK_List_S_compound_stmts",
  "XTOK_List_E_funCall_args",
  "XTOK_List_E_constructor_args",
  "XTOK_List_E_new_placementArgs",
  "XTOK_List_ArgExpressionListOpt_list",
  "XTOK_List_IN_compound_inits",
  "XTOK_List_IN_ctor_args",
  "XTOK_List_TP_template_parameters",
  "XTOK_List_IN_designated_designator_list",
  "XTOK_List_FullExpressionAnnot_declarations",
  "XTOK_List_AT_func_args",

  //  child attribute names
  // redundant token: access
  "XTOK_after",
  "XTOK_alias",
  "XTOK_alignment",
  "XTOK_annot",
  // redundant token: args
  "XTOK_array",
  "XTOK_arraySize",
  "XTOK_artificial",
  "XTOK_attr",
  "XTOK_atype",
  "XTOK_b",
  "XTOK_base",
  // redundant token: bases
  "XTOK_bits",
  "XTOK_body",
  "XTOK_branches",
  "XTOK_c",
  "XTOK_colonColon",
  "XTOK_cond",
  "XTOK_context",
  "XTOK_continuation",
  "XTOK_ctorArgs",
  "XTOK_ctorStatement",
  "XTOK_ctorVar",
  "XTOK_ctype",
  // redundant token: cv
  "XTOK_d",
  "XTOK_decl",
  "XTOK_declarations",
  "XTOK_decllist",
  "XTOK_defaultTemplate",
  "XTOK_defaultType",
  "XTOK_designator_list",
  "XTOK_dflags",
  "XTOK_dtorStatement",
  // redundant token: e
  "XTOK_e1",
  "XTOK_e2",
  "XTOK_el",
  "XTOK_elseBranch",
  "XTOK_elts",
  "XTOK_endloc",
  "XTOK_enumValue",
  "XTOK_etype",
  "XTOK_exnSpec",
  "XTOK_expr",
  "XTOK_exprHi",
  "XTOK_exprLo",
  "XTOK_f",
  "XTOK_fakeName",
  "XTOK_field",
  "XTOK_fieldName",
  "XTOK_form",
  "XTOK_forms",
  "XTOK_fullTextNQ",
  "XTOK_func",
  "XTOK_funcType",
  "XTOK_globalCtorStatement",
  "XTOK_globalDtorStatement",
  "XTOK_globalScope",
  "XTOK_globalVar",
  "XTOK_handlers",
  "XTOK_heapVar",
  // redundant token: i
  "XTOK_id",
  "XTOK_idx_computed",
  "XTOK_idx_computed2",
  "XTOK_idx_expr",
  "XTOK_idx_expr2",
  "XTOK_implicitlyDefined",
  "XTOK_init",
  "XTOK_inits",
  "XTOK_instFlags",
  "XTOK_isArray",
  "XTOK_isMember",
  "XTOK_isNew",
  "XTOK_isNewSize",
  "XTOK_isVirtual",
  "XTOK_k",
  "XTOK_kAndR_params",
  // redundant token: key
  "XTOK_keyword",
  "XTOK_labelName",
  "XTOK_labelVal",
  "XTOK_labelValHi",
  "XTOK_labelValLo",
  "XTOK_linkageType",
  "XTOK_list",
  // redundant token: loc
  "XTOK_localArg",
  "XTOK_member",
  "XTOK_members",
  // redundant token: name
  "XTOK_nameAndParams",
  "XTOK_nestedName",
  "XTOK_next",
  "XTOK_nondependentVar",
  "XTOK_numBits",
  "XTOK_o",
  "XTOK_obj",
  "XTOK_op",
  "XTOK_original",
  "XTOK_param",
  "XTOK_parameters",
  "XTOK_params",
  "XTOK_placementArgs",
  "XTOK_ptr",
  "XTOK_qualifier",
  "XTOK_qualifierVar",
  "XTOK_receiver",
  // redundant token: rest
  "XTOK_retObj",
  "XTOK_retVar",
  "XTOK_retspec",
  "XTOK_s",
  "XTOK_sargs",
  // redundant token: size
  "XTOK_spec",
  "XTOK_src",
  "XTOK_stmts",
  "XTOK_stype",
  "XTOK_target",
  "XTOK_tchecked",
  "XTOK_tcheckedType",
  "XTOK_td",
  "XTOK_templArgs",
  "XTOK_text",
  "XTOK_th",
  "XTOK_thenBranch",
  "XTOK_topForms",
  "XTOK_ttype",
  // redundant token: type
  "XTOK_typeId",
  "XTOK_typenameUsed",
  "XTOK_types",
  "XTOK_var",
  "XTOK_w",
  "XTOK_was_IN_expr",
