Freya3Dengine: core::multithreading::RingBuffer< T, sz > Class Template Reference
core::multithreading::RingBuffer< T, sz > Class Template Reference
This class is an abstraction of the ring buffer synchronization concept.
#include <RingBuffer.h>
Inherits EngineSubsystem.
Public Member Functions
T fetch ()
Retrieve a value from the buffer.
void deposit (const T &data)
Add an element to the buffer.
bool empty ()
Retrieve the state of buffer.
bool full ()
Retrieve the state of buffer.
size_t count ()
Retrieve the current buffers size.
Detailed Description
template<typename T, size_t sz>
class core::multithreading::RingBuffer< T, sz >
This class provides an abstract interface to the ring buffer synchronization primitive
Template Parameters:
T is a type of an object to be queued.
sz is a size of a buffer
Definition at line 29 of file RingBuffer.h.
Member Function Documentation
template<typename T , size_t sz> size_t core::multithreading::RingBuffer< T, sz >::count () [inline]
Retrieves the current size of buffer
Returns:
size of buffer
Definition at line 155 of file RingBuffer.h.
template<typename T , size_t sz> void core::multithreading::RingBuffer< T, sz >::deposit (const T & data) [inline]
Adds an element to the buffer, if there is any free space left. Otherwise, awaits until the buffer will contain enough space
Definition at line 125 of file RingBuffer.h.
References core::multithreading::Mutex::lock(), core::multithreading::Condition::signal(), core::multithreading::Mutex::unlock(), and core::multithreading::Condition::wait().
template<typename T , size_t sz> bool core::multithreading::RingBuffer< T, sz >::empty () [inline]
Checks the buffer state
Returns:
true if buffer is empty, false otherwise
Definition at line 141 of file RingBuffer.h.
template<typename T , size_t sz> T core::multithreading::RingBuffer< T, sz >::fetch () [inline]
Retrieves the next queued value from the buffer, if any available. Otherwise, awaits until the buffer is filled at least with one element
Returns:
next queued value.
Definition at line 106 of file RingBuffer.h.
References core::multithreading::Mutex::lock(), core::multithreading::Condition::signal(), core::multithreading::Mutex::unlock(), and core::multithreading::Condition::wait().
template<typename T , size_t sz> bool core::multithreading::RingBuffer< T, sz >::full () [inline]
Checks the buffer state
Returns:
true if buffer is full, false otherwise
Definition at line 148 of file RingBuffer.h.
The documentation for this class was generated from the following file:
RingBuffer.h
(c) 2008-2009 by Dmitri Vedenko and Vitalii Sverchinskii
Freya 3D engine is licenced under GNU GPL v3, yet we do not garantee that it will be always OpenSource