function ( GenerateStaticPluginsBuild )
	MESSAGE(STATUS "Generating StaticPluginsLoader.cpp")
	GET_PROPERTY ( FILESYSTEM_PLUGINS GLOBAL PROPERTY FILESYSTEM_PLUGINS_GLOBAL )
	GET_PROPERTY ( RENDERER_PLUGINS GLOBAL PROPERTY RENDERER_PLUGINS_GLOBAL )
	GET_PROPERTY ( RESOURCE_PLUGINS GLOBAL PROPERTY RESOURCE_PLUGINS_GLOBAL )
	GET_PROPERTY ( WINDOWMANAGER_PLUGINS GLOBAL PROPERTY WINDOWMANAGER_PLUGINS_GLOBAL )
	GET_PROPERTY ( INPUT_PLUGINS GLOBAL PROPERTY INPUT_PLUGINS_GLOBAL )
	MESSAGE(STATUS " Filesystem plugins: ${FILESYSTEM_PLUGINS}")
	MESSAGE(STATUS " Renderer plugins: ${RENDERER_PLUGINS}")
	MESSAGE(STATUS " Resource plugins: ${RESOURCE_PLUGINS}")
	MESSAGE(STATUS " Windowmanager plugins: ${WINDOWMANAGER_PLUGINS}")
	MESSAGE(STATUS " Input plugins (not implemented yet): ${INPUT_PLUGINS}")
	
	SET( SOURCE_CODE "#include \"core/EngineCore.h\"\n#include \"core/drivermodel/DriverID.h\"\n#include \"core/filesystem/Filesystem.h\"\n#include \"resources/ResourceManager.h\"\n\n" )
	
	SET( SOURCE_CODE "${SOURCE_CODE}void load_static_plugins()\n{\n" )
	#Parsing itself
	FOREACH(item ${FILESYSTEM_PLUGINS})
	SET( SOURCE_CODE "${SOURCE_CODE}\t//${item} prototypes\n" )
	SET( SOURCE_CODE "${SOURCE_CODE}\tunsigned ${item}_num_entries();\n\tcore::drivermodel::DriverID* ${item}_driver_id(unsigned);\n" )
	SET( SOURCE_CODE "${SOURCE_CODE}\tfor(unsigned i = 0;i < ${item}_num_entries();i++)\n\t\tcore::EngineCore::getFilesystem()->registerDriver( ${item}_driver_id (i));\n\n")
	ENDFOREACH( item )
	
	FOREACH(item ${RENDERER_PLUGINS})
	SET( SOURCE_CODE "${SOURCE_CODE}\t//${item} prototypes\n" )
	SET( SOURCE_CODE "${SOURCE_CODE}\tunsigned ${item}_num_entries();\n\tcore::drivermodel::DriverID* ${item}_driver_id(unsigned);\n" )
	SET( SOURCE_CODE "${SOURCE_CODE}\tfor(unsigned i = 0;i < ${item}_num_entries();i++)\n\t\tcore::EngineCore::registerRenderingDriver( ${item}_driver_id (i));\n\n")
	ENDFOREACH( item )
	
	FOREACH(item ${RESOURCE_PLUGINS})
	SET( SOURCE_CODE "${SOURCE_CODE}\t//${item} prototypes\n" )
	SET( SOURCE_CODE "${SOURCE_CODE}\tunsigned ${item}_num_entries();\n\tcore::drivermodel::DriverID* ${item}_driver_id(unsigned);\n" )
	SET( SOURCE_CODE "${SOURCE_CODE}\tfor(unsigned i = 0;i < ${item}_num_entries();i++)\n\t\tcore::EngineCore::getResourceManager()->registerDriver( ${item}_driver_id (i));\n\n")
	ENDFOREACH( item )
	
	FOREACH(item ${WINDOWMANAGER_PLUGINS})
	SET( SOURCE_CODE "${SOURCE_CODE}\t//${item} prototypes\n" )
	SET( SOURCE_CODE "${SOURCE_CODE}\tunsigned ${item}_num_entries();\n\tcore::drivermodel::DriverID* ${item}_driver_id(unsigned);\n" )
	SET( SOURCE_CODE "${SOURCE_CODE}\tfor(unsigned i = 0;i < ${item}_num_entries();i++)\n\t\tcore::EngineCore::registerWindowManager ( ${item}_driver_id (i));\n\n")
	ENDFOREACH( item )
	
	SET( SOURCE_CODE "${SOURCE_CODE}}\n" )
	FILE( WRITE ${INTERMIDIATE_DIRECTORY}/StaticPluginsLoader.cpp "${SOURCE_CODE}")
endfunction ( GenerateStaticPluginsBuild )